# Generated by Django 4.2 on 2024-05-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('receiver_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_message', to='users.customuser')),
            ],
        ),
    ]
