# Generated by Django 4.2 on 2024-05-15 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_message'),
        ('message', '0002_message_send_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_message', to='users.customuser'),
        ),
    ]
