# Generated by Django 4.2 on 2024-05-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('username', models.CharField(max_length=30, null=True, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('is_vip', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('receiver_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_message', to='users.customuser')),
                ('sender_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_message', to='users.customuser')),
            ],
        ),
    ]
