# Generated by Django 4.2 on 2024-05-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_message_sender_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
